### ISSUE TITLE
there is no transliteration for the character "ѝ" 

### ISSUE THREAD

**Issue by lordcris** [petarov/translitbg.js#1]
Using "ѝ" ex (майка ѝ) breaks the function. Could you please add it?
thanks

 
'Ѝ' : 'I'
'ѝ' : 'i'

**Comment by lordcris** [comment]
I've created a pull request

https://github.com/petarov/translitbg.js/pull/2

**Comment by petarov** [comment]
translit.bg uses [Обтекаема система ](https://bg.wikipedia.org/wiki/Транслитерация_на_българските_букви_с_латински). I  could not find explicit info about `Ѝ/ѝ` in its docs, but I guess the PR should suffice.

Thank you 🍺
